name: kd_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flutter_slidable: ^4.0.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.4
  path: ^1.9.1
  photo_view: ^0.15.0
  build_runner: ^2.4.15


 
dependency_overrides:
  floating: ^6.0.0
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/chatapp.png
    - assets/avatars/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/chatapp.png"