-keep class **.zego.** { *; }
-dontwarn com.itgsa.opensdk.mediaunit.KaraokeMediaHelper
-dontwarn java.beans.ConstructorProperties
-dontwarn java.beans.Transient
-dontwarn org.w3c.dom.bootstrap.DOMImplementationRegistry
